language: node_js
sudo: required
before_script:
  - npm install -g polymer-cli
  - polymer install --variants  
node_js: stable
addons:
  codeclimate:
    repo_token: b76ed4c614efcaac14fdb5b124660cd41dcf0d79ce1ebcd0b9b2c934b8e3e97e
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
script:
  - xvfb-run polymer test
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
after_script:
  - codeclimate-test-report < lcov.info
dist: trusty